#!/bin/bash
# Deploy Bedrock Invocation Analytics
# Usage:
#   ./deploy.sh hub [cdk-options]         Deploy primary account stack
#   ./deploy.sh spoke [profile]           Deploy spoke stack(s)
#   ./deploy.sh all                       Deploy hub + all spokes
#   ./deploy.sh [cdk-command]             Raw CDK command (diff, synth, destroy, etc.)
#
# Configuration: config.yaml

set -e
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
CONFIG="$SCRIPT_DIR/config.yaml"
ENV_FILE="$SCRIPT_DIR/.env.deploy"

if [[ ! -f "$CONFIG" ]]; then
    echo "Error: config.yaml not found"
    exit 1
fi

# Parse YAML config (lightweight, no external deps)
parse_yaml() {
    python3 -c "
import yaml, json, sys
with open('$CONFIG') as f:
    print(json.dumps(yaml.safe_load(f)))
"
}

CONFIG_JSON=$(parse_yaml)
PRIMARY_PROFILE=$(echo "$CONFIG_JSON" | python3 -c "import json,sys; accounts=json.load(sys.stdin)['accounts']; print(next(a['profile'] for a in accounts if a.get('primary')))")
PRIMARY_REGION=$(echo "$CONFIG_JSON" | python3 -c "import json,sys; accounts=json.load(sys.stdin)['accounts']; print(next(a['region'] for a in accounts if a.get('primary')))")
PRIMARY_BUCKET=$(echo "$CONFIG_JSON" | python3 -c "import json,sys; accounts=json.load(sys.stdin)['accounts']; print(next(a.get('bucket','') for a in accounts if a.get('primary')))")
LOG_PREFIX=$(echo "$CONFIG_JSON" | python3 -c "import json,sys; print(json.load(sys.stdin).get('log_prefix','bedrock/invocation-logs/'))")

# Get account ID for a profile
get_account_id() {
    aws sts get-caller-identity --profile "$1" --query Account --output text 2>/dev/null
}

run_cdk() {
    local profile="$1"; shift
    local region="$1"; shift
    export AWS_DEFAULT_REGION="$region"
    cd "$SCRIPT_DIR/deploy" && uv run --project .. cdk "$@" --profile "$profile"
}

CMD="${1:-}"
shift 2>/dev/null || true

case "$CMD" in
    hub)
        echo "=== Deploying Hub (${PRIMARY_PROFILE} / ${PRIMARY_REGION}) ==="
        HUB_ACCOUNT=$(get_account_id "$PRIMARY_PROFILE")

        # Auto-bootstrap if needed
        if ! aws cloudformation describe-stacks --profile "$PRIMARY_PROFILE" --region "$PRIMARY_REGION" \
            --stack-name CDKToolkit &>/dev/null; then
            echo "=== Bootstrapping CDK (${PRIMARY_PROFILE} / ${PRIMARY_REGION}) ==="
            run_cdk "$PRIMARY_PROFILE" "$PRIMARY_REGION" bootstrap
        fi

        # Collect spoke account IDs for SpokeWriteRole trust policy
        SPOKE_IDS=""
        SPOKE_ACCOUNTS=$(echo "$CONFIG_JSON" | python3 -c "
import json,sys
accounts=json.load(sys.stdin)['accounts']
for a in accounts:
    if not a.get('primary'):
        print(a['profile'])
")
        for sp in $SPOKE_ACCOUNTS; do
            ACCT_ID=$(get_account_id "$sp")
            if [[ -n "$ACCT_ID" ]]; then
                SPOKE_IDS="${SPOKE_IDS:+$SPOKE_IDS,}$ACCT_ID"
            fi
        done

        PARAMS="--parameters LogPrefix=${LOG_PREFIX}"
        [[ -n "$PRIMARY_BUCKET" ]] && PARAMS="$PARAMS --parameters ExistingBucketName=${PRIMARY_BUCKET}"

        SPOKE_CTX=""
        [[ -n "$SPOKE_IDS" ]] && SPOKE_CTX="-c spoke_accounts=${SPOKE_IDS}"

        run_cdk "$PRIMARY_PROFILE" "$PRIMARY_REGION" deploy \
            -c target=hub $SPOKE_CTX \
            $PARAMS --require-approval never "$@"

        # Save outputs to .env.deploy
        cat > "$ENV_FILE" <<EOF
# Auto-generated by deploy.sh
PRIMARY_PROFILE="${PRIMARY_PROFILE}"
PRIMARY_REGION="${PRIMARY_REGION}"
HUB_ACCOUNT="${HUB_ACCOUNT}"
USAGE_STATS_TABLE="BedrockInvocationAnalytics-usage-stats"
MODEL_PRICING_TABLE="BedrockInvocationAnalytics-model-pricing"
SPOKE_WRITE_ROLE_ARN="arn:aws:iam::${HUB_ACCOUNT}:role/BedrockAnalytics-SpokeWriteRole"
EOF
        echo "=== Hub deployed. Config saved to .env.deploy ==="
        ;;

    spoke)
        TARGET_PROFILE="${1:-}"
        HUB_ACCOUNT=$(get_account_id "$PRIMARY_PROFILE")

        SPOKES=$(echo "$CONFIG_JSON" | python3 -c "
import json,sys
accounts=json.load(sys.stdin)['accounts']
for a in accounts:
    if not a.get('primary'):
        print(f\"{a['profile']}:{a['region']}:{a.get('bucket','')}\")" )

        for spoke_info in $SPOKES; do
            IFS=: read -r profile region bucket <<< "$spoke_info"
            [[ -n "$TARGET_PROFILE" && "$profile" != "$TARGET_PROFILE" ]] && continue

            # Auto-bootstrap if needed
            if ! aws cloudformation describe-stacks --profile "$profile" --region "$region" \
                --stack-name CDKToolkit &>/dev/null; then
                echo "=== Bootstrapping CDK (${profile} / ${region}) ==="
                run_cdk "$profile" "$region" bootstrap
            fi

            STACK_ID="BedrockAnalytics-Spoke-${profile}-${region}"
            echo "=== Deploying Spoke (${profile} / ${region}) ==="
            PARAMS="--parameters ${STACK_ID}:LogPrefix=${LOG_PREFIX}"
            [[ -n "$bucket" ]] && PARAMS="$PARAMS --parameters ${STACK_ID}:ExistingBucketName=${bucket}"

            run_cdk "$profile" "$region" deploy "$STACK_ID" \
                -c target="spoke:${profile}" \
                -c hub_account="$HUB_ACCOUNT" \
                $PARAMS --require-approval never "$@"

            echo "=== Spoke ${profile}/${region} deployed ==="
        done
        ;;

    all)
        "$SCRIPT_DIR/deploy.sh" hub "$@"
        "$SCRIPT_DIR/deploy.sh" spoke "$@"
        ;;

    *)
        # Raw CDK command (diff, synth, destroy, etc.)
        run_cdk "$PRIMARY_PROFILE" "$PRIMARY_REGION" "$CMD" "$@"
        ;;
esac
