#!/bin/bash
# Deploy CDK stack
# Usage: ./deploy.sh [cdk-command] [options]
# First deploy saves config to .env.deploy; subsequent deploys reuse them.
# Examples:
#   ./deploy.sh deploy --profile me --bucket central-logs-xxx-us-west-2
#   ./deploy.sh deploy              # reuses saved config
#   ./deploy.sh diff

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ENV_FILE="$SCRIPT_DIR/.env.deploy"

# Load saved config
[[ -f "$ENV_FILE" ]] && source "$ENV_FILE"

# Parse args: extract custom flags
ARGS=("$@")
for i in "${!ARGS[@]}"; do
    case "${ARGS[$i]}" in
        --profile) PROFILE="${ARGS[$((i+1))]}" ;;
        --region)  REGION="${ARGS[$((i+1))]}" ;;
        --bucket)  EXISTING_BUCKET_NAME="${ARGS[$((i+1))]}" ; unset 'ARGS[$i]' 'ARGS[$((i+1))]' ;;
        --prefix)  LOG_PREFIX="${ARGS[$((i+1))]}" ; unset 'ARGS[$i]' 'ARGS[$((i+1))]' ;;
    esac
done
ARGS=("${ARGS[@]}")

# Capture region from env var if not set
[[ -z "$REGION" && -n "$AWS_DEFAULT_REGION" ]] && REGION="$AWS_DEFAULT_REGION"

# Inject saved profile
[[ -n "$PROFILE" && ! " $* " =~ " --profile " ]] && ARGS+=(--profile "$PROFILE")

# Set region
[[ -n "$REGION" ]] && export AWS_DEFAULT_REGION="$REGION"

# On deploy/bootstrap: save config and inject parameters
CMD="${ARGS[0]}"
if [[ "$CMD" == "deploy" || "$CMD" == "bootstrap" ]]; then
    cat > "$ENV_FILE" <<EOF
# Auto-generated by deploy.sh
PROFILE="${PROFILE}"
REGION="${REGION}"
EXISTING_BUCKET_NAME="${EXISTING_BUCKET_NAME}"
LOG_PREFIX="${LOG_PREFIX:-bedrock/invocation-logs/}"
EOF

    [[ -n "$EXISTING_BUCKET_NAME" ]] && ARGS+=(--parameters "ExistingBucketName=${EXISTING_BUCKET_NAME}")
    ARGS+=(--parameters "LogPrefix=${LOG_PREFIX:-bedrock/invocation-logs/}")
fi

cd "$SCRIPT_DIR/deploy" && uv run --project .. cdk "${ARGS[@]}"
